[[PATHlib]]
arch = "i686"
git-tree-sha1 = "be5550ee04382da193d29f44af82afbebdd7ae5e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "1444a3646d6081fe105f7aff6821e569f4901379d24c1370b55caaa8a15ea3b9"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.i686-linux-gnu-libgfortran3.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "7441a9ea154ecd3b0d2527111a16bdd14882c6d1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "d178b001dcfb308a6da556c19525de52dd6e4987584c1e7fd3f5690f6b0ba269"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.i686-linux-gnu-libgfortran4.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "4aef0a8b919f187f6321b071fa8306d9c8027199"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "9df4f00db293cd1b97ec7085a381d12a58a8baa63b56dd27ade654ed6d961314"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.i686-linux-gnu-libgfortran5.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "fbbc7e78b9c6e13b82fd581db86af5b87477251b"
libgfortran_version = "3.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "5f4f62f82e19d523e19b8ee91857f894ce3a9ce0d7051c8164e0ff36e8d9cc83"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.i686-w64-mingw32-libgfortran3.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "ffffb383e17bc996fe3000694122f37263c7fc7a"
libgfortran_version = "4.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "542767c2656a4bd887dd8ad013c3133c209a9ea9fa46c2cab44446e06445b476"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.i686-w64-mingw32-libgfortran4.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "3ff28497ec005de9b0c18097115163200bc7c470"
libgfortran_version = "5.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "ae65ba6ef68963b72cf795c3730cafa27cdcadedb730f0e0267acbfb659a816f"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "266891f9d70c671d16543e569c520e172f2143dd"
libgfortran_version = "3.0.0"
os = "macos"

    [[PATHlib.download]]
    sha256 = "2120351762d900f23047d58a5fb90611e4e75ed3358813f2206c03a85f55657e"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "987493c6e42a04f6ab388fc51d5da1165db60637"
libgfortran_version = "4.0.0"
os = "macos"

    [[PATHlib.download]]
    sha256 = "3ef139ee387827401d9518d38bce4f5af649f972027531bde4ac378868e34ba1"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "148bfd7cf738a711a1ccb5cd6df3bdedaf2facd0"
libgfortran_version = "5.0.0"
os = "macos"

    [[PATHlib.download]]
    sha256 = "7e934837838a336b3459e3c46a29cd014b019c4976def026a58cab3e411185d3"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "d9e21f836fc99148513512c29d7a2269a89faaf0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "cc97a47c9b5a1c4611dfcce3a9d2c10ba2a419e03769d6f77de131376426d15d"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "dc566016b63ef539fc6d110b51485934bd330db8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "3ee49c4ea5fcae71449e69553df5ffe0b8e5540158a0809062e28184797883e3"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "6a087bb925645d964cd9fab7c72832de193d4369"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "52ec2d85ee28230a81b2b87c450449adf115f3c5e81b4f7b712499dca3922d05"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "8c74b0843dd01a5a7c05195342246084a7777180"
libgfortran_version = "3.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "8384b8b6d70414debd5bc73ad77a258c6f8656a4042bcb697dc252e194651447"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "e0a210b2778c0f892a2854381cf60b729b005264"
libgfortran_version = "4.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "710a82d671fc54f8ad1dcb92ca0684729d338c1097793fa1f49877ad93ca3a80"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "b5105af80155308dd52c019fedafc4ab412cf3c5"
libgfortran_version = "5.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "de0286bdf948e7269fac892a64fe32550fd08aa8c886fc868a24e8a147fa5e48"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+1/PATHlib.v4.7.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
