# Autogenerated wrapper script for PATHlib_jll for x86_64-w64-mingw32-libgfortran4
export libpath47julia

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("PATHlib")
JLLWrappers.@declare_library_product(libpath47julia, "libpath47julia.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libpath47julia,
        "bin\\libpath47julia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
